/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9f97fd52-9405-4813-863c-74fad278a4fd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vuqzih3nD",
    "aws_user_pools_web_client_id": "7kc9gisuif5t7e587sar6h96d4",
    "oauth": {}
};


export default awsmobile;
